language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1.18
    - php: 7.2
    - php: 7.3

before_install:
  - composer self-update
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - phpunit
  
script: phpunit --bootstrap vendor/autoload.php tests/SyntaxoTest