language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1.3
  - 7.2
  - 7.3

install:
  - composer install
  
script: phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests/SyntaxoTest