language: php
install:
  - composer install
before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com
script: phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests