language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1.18
    - php: 7.2
    - php: 7.3

before_install:
  - composer self-update

install:
  - composer install
  
before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com
  
script: phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests